import { NextResponse } from 'next/server'
import { getServerSupabase } from '@/lib/supabase'

// Count sheet from 6/22/2026 – { name, category (if needed to disambiguate), count }
const counts: { name: string; category?: string; count: number }[] = [
  // Containers & Cups
  { name: 'Kids Ice Cups', count: 4.25 },
  { name: 'Small Ice Cups', count: 1 },
  { name: 'Large Ice Cups', count: 1 },
  { name: 'Quarts', count: 1 },
  { name: 'Ice Flights', count: 5 },
  { name: 'Gallon Containers', count: 1 },
  { name: '2.5 Gallon Containers', count: 1 },
  { name: '1st Day Spring Cups', count: 0 },
  { name: 'Small Custard Cups', count: 1.25 },
  { name: 'Large Custard Cups', count: 0 },
  { name: 'Large Sundae Bowls', count: 0 },
  { name: 'Pints', count: 2 },
  { name: 'Small Milkshake Cups', count: 0.75 },
  { name: 'Large Milkshake Cups', count: 1.25 },
  { name: 'Individual Hinged Cookie Containers', count: 0.75 },
  { name: '6-Pack Cookie Containers', count: 0.75 },
  { name: 'Food Boats (Small)', count: 0.75 },
  // Lids
  { name: 'Kids Ice Cup Lids', count: 1.25 },
  { name: 'Small Ice Cup Lids', count: 1 },
  { name: 'Large Ice Cup Lids', count: 0.5 },
  { name: 'Quart Ice Cup Lids', count: 1 },
  { name: 'Ice Flight Lids', count: 6 },
  { name: 'Gallon Lids', count: 1 },
  { name: 'Small/Large Custard Cup Lids', count: 0.75 },
  { name: 'Large Sundae Bowl Lids', count: 0.5 },
  { name: 'Pint Lids', count: 1.25 },
  { name: 'Small Hole Milkshake Lids', count: 1.5 },
  { name: 'Large Hole Milkshake Lids', count: 0.5 },
  { name: 'Topping Cup Lids', count: 0.75 },
  // Spoons & Straws
  { name: 'Regular Spoons', count: 7 },
  { name: 'Long Spoons', count: 1 },
  { name: 'Sample Spoons', count: 0 },
  { name: 'Small Straws', count: 0 },
  { name: 'Large Straws', count: 1 },
  // Topping Containers
  { name: "Rita's Logo Topping Cups", count: 1.25 },
  { name: 'Translucent Plastic Topping Cups', count: 1.25 },
  { name: 'Paper Souffle/Sample Cups', count: 0.5 },
  // Toppings - Dry
  { name: 'Graham Crackers', count: 0 },
  { name: 'Nilla Wafers', count: 0.25 },
  { name: 'M&Ms', count: 1 },
  { name: 'Peppermint', count: 1 },
  { name: 'Peanuts', count: 2 },
  { name: 'Gummy Bears', count: 0.75 },
  { name: 'Oreo Pieces', count: 0 },
  { name: 'Chocolate Sprinkles', count: 1 },
  { name: 'Rainbow Sprinkles', count: 1 },
  { name: 'Glitter Sprinkles', count: 0 },
  { name: "Reese's Cups", count: 0.25 },
  { name: 'Chocolate Chips', count: 1 },
  { name: 'Take 5', count: 0.25 },
  { name: 'Cookie Dough Bites', count: 1 },
  { name: 'Brownie Bites', count: 1.25 },
  { name: 'Unicorn Bark', count: 0.5 },
  { name: 'Baby Nerds', count: 1.25 },
  { name: 'Regular Nerds', count: 0 },
  { name: 'Skittles', category: 'Toppings - Dry', count: 0 },
  { name: 'Almond Roca', count: 1 },
  { name: 'Andes', count: 1 },
  { name: 'Tajin', count: 2 },
  { name: 'Tamarind Candy', count: 2 },
  { name: 'Brownies (for sundaes)', count: 0 },
  { name: 'Peeps', category: 'Toppings - Dry', count: 0.25 },
  { name: 'Sour Dust', count: 4 },
  // Toppings - Wet
  { name: 'Peanut Butter Topping', count: 4 },
  { name: 'Crushed Cherries', count: 5 },
  { name: 'Diced Black Cherries', count: 2 },
  { name: 'Apple Topping', count: 3 },
  { name: 'Strawberry Topping', count: 4 },
  { name: 'Pumpkin Cream Topping', count: 0 },
  { name: 'Whole Cherries', count: 3 },
  { name: 'Pineapple Topping', count: 2 },
  { name: 'Caramel', count: 5 },
  { name: 'Hot Fudge', count: 7 },
  { name: 'Whipped Cream', count: 11 },
  { name: 'Nacho Cheese', count: 0 },
  { name: 'Chamoy', count: 3 },
  { name: 'Butter', count: 0 },
  // Syrups
  { name: 'Banana', category: 'Syrups', count: 3.25 },
  { name: 'Black Raspberry', count: 0.5 },
  { name: 'Butter Pecan', count: 0.25 },
  { name: 'Cake Batter', count: 1.75 },
  { name: "Campfire S'mores", count: 0.5 },
  { name: 'Cheesecake', category: 'Syrups', count: 5.5 },
  { name: 'Coffee', count: 1.5 },
  { name: 'Cotton Candy', category: 'Syrups', count: 4 },
  { name: 'Mint', count: 4.5 },
  { name: 'Peach', count: 3 },
  { name: 'Pistachio', count: 5.25 },
  { name: 'Pumpkin', category: 'Syrups', count: 0.75 },
  { name: 'Strawberry', category: 'Syrups', count: 4.25 },
  // Ice Mix
  { name: 'Banana / Banana Split', count: 11.25 },
  { name: 'Birthday Cake', count: 2 },
  { name: 'Blue Raspberry', count: 3.5 },
  { name: 'Cheesecake', category: 'Ice Mix', count: 1.5 },
  { name: 'Cherry', count: 0.75 },
  { name: 'Clementine', count: 9 },
  { name: 'Cola', count: 8 },
  { name: 'Coconut Cream', count: 4 },
  { name: 'Cookies N Cream', count: 5.5 },
  { name: 'Cotton Candy', category: 'Ice Mix', count: 6 },
  { name: 'Georgia Peach', count: 3.5 },
  { name: 'Green Apple', count: 2.75 },
  { name: 'Gummy Bear', count: 3.5 },
  { name: 'Island Fusion', count: 0 },
  { name: 'Key Lime', count: 7 },
  { name: 'Koolaid Sharkleberry', count: 3.25 },
  { name: 'Koolaid Tropical Punch', count: 4.75 },
  { name: 'Lemon', count: 5.25 },
  { name: 'Mango', count: 3.75 },
  { name: 'Mint Chip', count: 4 },
  { name: 'Passionfruit Paloma', count: 10.5 },
  { name: 'Pina Colada', count: 4.5 },
  { name: 'Pineapple', category: 'Ice Mix', count: 0.5 },
  { name: 'Purple Candy', count: 2.25 },
  { name: 'Pumpkin', category: 'Ice Mix', count: 3 },
  { name: 'Raspberry', count: 0 },
  { name: 'Root Beer', count: 3 },
  { name: 'Skittles', category: 'Ice Mix', count: 2.5 },
  { name: "S'mores", count: 1.75 },
  { name: 'Sour Patch Watermelon', count: 1.25 },
  { name: 'Swedish Fish', count: 6 },
  { name: 'Strawberry', category: 'Ice Mix', count: 4.25 },
  { name: 'Vanilla', category: 'Ice Mix', count: 2.5 },
  { name: 'Watermelon', count: 7 },
  { name: 'Wild Cherry', count: 3.25 },
  { name: 'Peeps', category: 'Ice Mix', count: 0.25 },
  { name: 'Chocolate', category: 'Ice Mix', count: 2.75 },
  { name: 'Blackberry', count: 2 },
  { name: 'Sour Patch Kids Red', count: 3.25 },
  { name: 'Kiwi Melon', count: 1.5 },
  { name: 'Juicy Pear', count: 6.5 },
  { name: 'Sour Blue Pucker', count: 4 },
  { name: 'Sugar Free Dragon Fruit', count: 5 },
  { name: 'Sugar Free Mango Peach', count: 0 },
  { name: 'Sugar Free Cherry', count: 2 },
  { name: 'Sugar Free Pink Lemonade', count: 2 },
  { name: 'Mermaid', count: 4.5 },
  { name: 'Blue Hawaii', count: 3.5 },
  // Custard
  { name: 'Vanilla Custard Bags', count: 13.5 },
  { name: 'Chocolate Custard Bags', count: 3.5 },
  // Things to Make Ice
  { name: 'Sugar', category: 'Things to Make Ice', count: 0 },
  { name: 'Cream Ice Powder', count: 0.5 },
  { name: 'Chocolate Base', count: 2 },
  { name: 'Milkshake Syrup', count: 3 },
  { name: 'Milk', count: 0.25 },
  { name: 'Lemon Concentrate', count: 0.75 },
  { name: 'Lime Concentrate', count: 0.25 },
  // Cones
  { name: 'Waffle Cones', count: 0.75 },
  { name: 'Cake Cones', count: 1 },
  { name: 'Waffle Bowls', count: 2 },
  // Cookies
  { name: 'Chocolate Chip Cookies', count: 1.25 },
  { name: 'Peanut Butter Cookies', count: 2.75 },
  { name: 'Sugar Cookies', count: 1.5 },
  { name: 'Red Velvet Cookies', count: 0 },
  { name: 'Macadamia Nut Cookies', count: 0 },
  { name: 'Oreo Wafers (for sandwiches)', count: 1.5 },
  { name: 'Chocolate Chip Cookie Sandwiches', count: 1.5 },
  // Drink Items
  { name: 'Cold Brew Concentrate', count: 4 },
  { name: 'Matcha Syrup', count: 1 },
  { name: 'Water Bottles', count: 0 },
  // Bags & Carriers
  { name: 'Cookie Bags', count: 0.5 },
  { name: 'Plastic Bags', count: 1 },
  { name: "Small Rita's Paper Bags", count: 0.75 },
  { name: "Large Rita's Paper Bags", count: 0.5 },
  { name: 'Drink Carriers', count: 1 },
  // Napkins & Paper
  { name: 'White Napkins', count: 0 },
  { name: 'Paper Towels', count: 0.5 },
  { name: 'Brown Small Napkins', count: 1.25 },
  { name: 'Pink Rags', count: 2 },
  // Cleaning Supplies
  { name: 'Hand Soap', count: 0.25 },
  { name: 'Dish Soap', count: 0 },
  { name: 'Glass Cleaner', count: 4 },
  { name: 'Ajax', count: 3 },
  { name: 'Clorox Surface Cleaner', count: 0.25 },
  { name: 'Stainless Steel Cleaner', count: 1.75 },
  { name: 'Scour Pads', count: 3 },
  { name: 'Pine-Sol', count: 0.75 },
  { name: 'Neutral Cleaner', count: 0.75 },
  { name: 'Sanitizer', count: 2 },
  { name: 'Bleach', count: 0.25 },
  // Bathroom Supplies
  { name: 'Toilet Paper', count: 1 },
  { name: 'Toilet Seat Covers', count: 0 },
  // Trash Bags
  { name: 'White Trash Bags', count: 1.5 },
  { name: 'Black Trash Bags', count: 1.75 },
  { name: 'M Gloves', count: 0.75 },
  { name: 'L Gloves', count: 0.75 },
  // Stickers & Receipts
  { name: 'DoorDash Stickers', count: 2 },
  { name: "Small Rita's Red Stickers", count: 0 },
  { name: 'Cookie Sandwich Stickers', count: 4 },
  { name: 'Cookie Sandwich Ingredient Stickers', count: 4 },
  { name: 'Receipt Paper', count: 4 },
]

export async function POST() {
  const db = getServerSupabase()
  const errors: string[] = []
  let updated = 0

  for (const c of counts) {
    let query = db.from('items').update({ current_count: c.count }).eq('name', c.name)
    if (c.category) query = query.eq('category', c.category)

    const { error } = await query
    if (error) errors.push(`${c.name}: ${error.message}`)
    else updated++
  }

  return NextResponse.json({ updated, errors })
}
